# Generated by Django 5.2.11 on 2026-02-18 18:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_blogpost_category"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Biography and description of the author"
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        blank=True, help_text="Year of birth (optional)", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description for the events calendar page"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Optional subtitle", max_length=300
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Detailed description of the book"
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(
                        blank=True, help_text="Year of publication", null=True
                    ),
                ),
                (
                    "book_type",
                    models.CharField(
                        blank=True,
                        help_text="Category or type of book (e.g., Fiction, Reference, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all authors for this book",
                        related_name="books",
                        to="home.authorpage",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Book cover image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description of the event"
                    ),
                ),
                (
                    "event_date",
                    models.DateField(help_text="Date when the event will happen"),
                ),
                (
                    "event_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time when the event will happen",
                        null=True,
                    ),
                ),
                (
                    "event_link",
                    models.URLField(
                        blank=True,
                        help_text="Link for video call or event details (e.g., Zoom, Meet, etc.)",
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select all books related to this event",
                        related_name="events",
                        to="home.bookpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
