# Generated by Django 5.2.11 on 2026-03-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_authorpage_eventindexpage_bookpage_eventpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="featured_post",
            field=models.BooleanField(default=False, help_text="Mark as featured post"),
        ),
    ]
