# Generated by Django 5.2.11 on 2026-03-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_blogpost_featured_post"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorpage",
            name="author_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Author profile image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
